service: ukr-pepe-bot

provider:
  name: aws
  runtime: rust
  region: eu-central-1
  memorySize: 128

plugins:
  - serverless-rust

package:
  individually: true

custom:
  rust:
    dockerless: true
    # allow local running on ARM macs
    target: aarch64-apple-darwin
#    linker: clang

functions:
  test:
    handler: hello_world
    events:
      - http:
          path: /test
          method: GET
  v1_dialog_completing:
    handler: v1_dialog_completing
    timeout: 30
    environment:
      OPENAI_API_KEY: ${file(credentials.yaml):OPENAI_API_KEY}
    events:
      - http:
          path: /dialog-completions
          method: POST
